language: ruby

rvm:
  - "2.3.0"
  - "2.3.6"
  - "2.4.1"
  - "2.5.0"

env:
  - "RAILS_VERSION=rails4"
  - "RAILS_VERSION=pojs"

sudo: false

script: "if [ $PERFORMANCE_SPECS ];then bundle exec rake performance_specs --trace; else bundle exec rake --trace; fi"

install:
  - bundle install --retry=3

matrix:
  fast_finish: true
  include:
    - rvm: "2.3.4"
      env:
        - "PERFORMANCE_SPECS=true"
        - "RAILS_VERSION=rails5"
    - rvm: "2.3.4"
      env: "RAILS_VERSION=rails5"
  allow_failures:
    - rvm: "jruby-9.1.5.0"
      env:
        - "RAILS_VERSION=rails4"
        - "JRUBY_OPTS=''"

before_install:
  - gem update --system
  - gem install bundler -v "= 1.15.4"
